# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.21.0.0/16

google_assistant:
  project_id: !secret google_project_id
  service_account: !secret google_service_account
  report_state: true
  exposed_domains:
    - switch
    - light
    - climate
    - media_player
    - input_boolean

input_boolean:
  google_test_switch:
    name: "Google Test Switch"
    icon: mdi:power

recorder:
  db_url: !secret db_connection_url
  purge_keep_days: 7
  exclude:
    domains:
      - update
      - systemmonitor
    entity_globs:
      - sensor.glances_*
      - sensor.speedtest_*

