# Use this file to store secrets like usernames and passwords.
# Learn more at https://www.home-assistant.io/docs/configuration/secrets/
some_password: welcome

# Google Assistant Developer Bridge secrets
google_project_id: "hot-home"
google_service_account:
  private_key: "───BEGIN PRIVATE KEY───\nPASTE_YOUR_1700_CHAR_LONG_PRIVATE_KEY_FROM_JSON_HERE\n───END PRIVATE KEY───\n"
  client_email: "home-assistant@hot-home.iam.gserviceaccount.com"
