# Use this file to store secrets like usernames and passwords.
# Learn more at https://www.home-assistant.io/docs/configuration/secrets/
some_password: welcome

# Google Assistant Developer Bridge secrets
google_project_id: "PLACEHOLDER_PROJECT_ID"
google_service_account:
  private_key: "PLACEHOLDER_PRIVATE_KEY"
  client_email: "PLACEHOLDER_CLIENT_EMAIL"
