# widgets.yaml - Global dashboard header widgets
- datetime:
    text_size: l
    format:
      timeStyle: short
      dateStyle: medium

- search:
    provider: google
    target: _blank
    placeholder: SEARCH PROTOCOL...

- glances:
    url: http://glances:61208
    label: server
    cpu: true
    ram: true
    temp: true # Displays CPU temperatures!
    network: eth0 # Displays real-time network interface speeds!

- openmeteo:
    label: Oshawa
    latitude: 43.8971
    longitude: -78.8658
    units: metric
